services:
  backend:
    build: 
      context: ./backend
    ports:
      - "9991:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # 🌟 เชื่อมต่อกับ MariaDB (ค่าต้องตรงกับฝั่ง db_broker ด้านล่าง)
      - DB_HOST=db_broker
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_DATABASE=brokerdb
    depends_on:
      - db_broker
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    ports:
      - "9990:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9991/api
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - appnet

  phpmyadmin_broker:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_broker
    ports:
      - "9993:80"
    environment:
      PMA_HOST: db_broker
      PMA_PORT: 3306
    depends_on:
      - db_broker
    networks:
      - appnet

  db_broker:
    image: mariadb:10.5
    container_name: db_broker
    restart: unless-stopped
    # 🌟 เซตค่า Environment ตรงนี้แทนการใช้ไฟล์ภายนอก
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=brokerdb
    ports:
      - "3309:3306"
    volumes:
      - db_broker_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - appnet
volumes:
  db_broker_data:

networks:
  appnet:
    driver: bridge